Use_priors correction: using xfm when turned On only
FCP-INDI/C-PAC pull request #1609
Opened 2021-11-02 17:52 UTC by amygutierrez

## Fixes
Making sure that if use_priors is used, that it uses xfm. otherwise, xfm = None.

## Description

This pull request will assign `...image_desc-linear_xfm` if `use_priors` is turned on. Otherwise, xfm is not used. 

## Tests
Used a blank default pipeline and set `use_priors` to `Off`. No longer receiving this error `KeyError: "When trying to connect node block 'tissue_seg_ants_prior' to workflow 'cpac_sub-5289383_ses-1' after node block 'correct_restore_brain_intensity_abcd': from-template_to-T1w_mode-image_desc-linear_xfm"` Since `use_priors` is off, then xfm is not being used, therefore `from-template_to-T1w_mode-image_desc-linear_xfm` should not be used either.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [ x] My commit messages follow best practices.
- [ x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2021-11-02 18:53 UTC, shnizzedy approved these changes

2021-11-04 22:28 UTC, sgiavasis requested changes
This just needs to also be under a `if use_priors:` conditional:

https://github.com/FCP-INDI/C-PAC/blob/use-priors_correction/CPAC/seg_preproc/seg_preproc.py#L678-L681

Otherwise I'm getting this:

> Connecting anatomical_init...
> 
> Connecting brain_mask_afni...
> 
> Connecting brain_extraction...
> 
> Connecting tissue_seg_fsl_fast...
> 
> Traceback (most recent call last):
>   File "/code/run.py", line 698, in <module>
>     test_config = 1 if args.analysis_level == "test_config" else 0
>   File "/code/CPAC/pipeline/cpac_runner.py", line 549, in run
>     p_name, plugin, plugin_args, test_config)
>   File "/code/CPAC/pipeline/cpac_pipeline.py", line 396, in run_workflow
>     subject_id, sub_dict, c, p_name, num_ants_cores
>   File "/code/CPAC/pipeline/cpac_pipeline.py", line 1282, in build_workflow
>     wf = connect_pipeline(wf, cfg, rpool, pipeline_blocks)
>   File "/code/CPAC/pipeline/cpac_pipeline.py", line 971, in connect_pipeline
>     wf = nb.connect_block(wf, cfg, rpool)
>   File "/code/CPAC/pipeline/engine.py", line 1202, in connect_block
>     pipe_x, opt)
>   File "/code/CPAC/seg_preproc/seg_preproc.py", line 678, in tissue_seg_fsl_fast
>     node, out = strat_pool.get_data(xfm)
>   File "/code/CPAC/pipeline/engine.py", line 264, in get_data
>     return self.get(resource)['data']
>   File "/code/CPAC/pipeline/engine.py", line 235, in get
>     raise LookupError("\n\n[!] C-PAC says: The listed resource is "
> LookupError: When trying to connect node block 'tissue_seg_ants_prior' to workflow 'cpac_sub-0050952_ses-1' after node block 'correct_restore_brain_intensity_abcd': 
> 
> [!] C-PAC says: The listed resource is not in the resource pool:
> None
> 
> Developer Note: This may be due to a mismatch between the node block's docstring 'input' field and a strat_pool.get_data() call within the block function.

2021-11-05 14:25 UTC, shnizzedy approved these changes

2021-11-05 19:07 UTC, sgiavasis commented
Nice work!

2021-11-05 19:07 UTC, merged